name: ControlPlayer
version: 2.0.1
main: de.rayzs.controlplayer.plugin.ControlPlayerPlugin
author: Rayzs_YT
api-version: 1.13

commands:
  controlplayer:
    aliases: [cp, cplayer, controlp]
    description: Control the movement of a player