name: ControlPlayer
version: 2.0.0
main: de.rayzs.controlplayer.plugin.ControlPlayerPlugin
author: Rayzs_YT

commands:
  controlplayer:
    aliases: [cp, cplayer, controlp]
    description: Control the movement of a player