name: ControlPlayer
version: 2.2.5
main: de.rayzs.controlplayer.plugin.ControlPlayerPlugin
author: Rayzs_YT
api-version: 1.13

commands:
  controlplayer:
    aliases: [cp, cplayer, controlp, control]
    description: Control the movement of a player

  controlplayerreload:
    aliases: [cpr, controlplayerr, cpreload]
    description: Reload all files