# This one is just an example
# Please refer to the ingame commands instead!
#
# /wac <name> <armor-slot-type> | Create
# /wad <name> <armor-slot-type> | Delete
# /warl                         | Reload
spacehelmet:
  armor-slot-type: HELMET
  item:
    ==: org.bukkit.inventory.ItemStack
    v: 4189
    type: LIGHT_BLUE_STAINED_GLASS