name: WearAnything
version: 0.0.1
author: Rayzs_YT
main: de.rayzs.wearanything.plugin.loader.WearAnythingBukkitLoader

commands:
  wearanythingreload:
    description: Reload the config file.
    aliases: [wearanythingrl, wareload, warl]
    permission: wearanything.reload

  wearanythingcreate:
    description: Create a wearable item index.
    aliases: [wac, wearanythingc]
    permission: wearanything.create

  wearanythingdelete:
    description: Delete a wearable item index.
    aliases: [wad, wearanythingd]
    permission: wearanything.delete