package de.rayzs.controlplayer.api.files.message;

public enum MessageType {
    PREFIX, USAGE,
    BEING_CONTROLLED, SUCCESS, ERROR, NO_PERMISSION,
    ONLY_PLAYERS, STOPPED_CONTROLLING,
    ALREADY_CONTROLLED, PLAYER_IMUN,
    SELF_CONTROL, NOT_ONLINE, PLAYER_LEFT, PLAYER_DIED,
    ACTIONBAR_TEXT
}
